// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kodama.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_OK      ErrCode = 0
	ErrCode_BUSY    ErrCode = 1
	ErrCode_GENERIC ErrCode = 100
)

var ErrCode_name = map[int32]string{
	0:   "OK",
	1:   "BUSY",
	100: "GENERIC",
}
var ErrCode_value = map[string]int32{
	"OK":      0,
	"BUSY":    1,
	"GENERIC": 100,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_kodama_955673a68b9e6acd, []int{0}
}

type Job struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_kodama_955673a68b9e6acd, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_kodama_955673a68b9e6acd, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Error struct {
	ErrCode              ErrCode  `protobuf:"varint,1,opt,name=errCode,proto3,enum=service.ErrCode" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_kodama_955673a68b9e6acd, []int{2}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrCode() ErrCode {
	if m != nil {
		return m.ErrCode
	}
	return ErrCode_OK
}

func init() {
	proto.RegisterType((*Job)(nil), "service.Job")
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*Error)(nil), "service.Error")
	proto.RegisterEnum("service.ErrCode", ErrCode_name, ErrCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KodamaClient is the client API for Kodama service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KodamaClient interface {
	Push(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Error, error)
}

type kodamaClient struct {
	cc *grpc.ClientConn
}

func NewKodamaClient(cc *grpc.ClientConn) KodamaClient {
	return &kodamaClient{cc}
}

func (c *kodamaClient) Push(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/service.Kodama/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KodamaServer is the server API for Kodama service.
type KodamaServer interface {
	Push(context.Context, *Job) (*Error, error)
}

func RegisterKodamaServer(s *grpc.Server, srv KodamaServer) {
	s.RegisterService(&_Kodama_serviceDesc, srv)
}

func _Kodama_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KodamaServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Kodama/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KodamaServer).Push(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kodama_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Kodama",
	HandlerType: (*KodamaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Kodama_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kodama.proto",
}

func init() { proto.RegisterFile("kodama.proto", fileDescriptor_kodama_955673a68b9e6acd) }

var fileDescriptor_kodama_955673a68b9e6acd = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0x80, 0x40,
	0x10, 0x46, 0xb5, 0xd4, 0xad, 0x51, 0x64, 0x99, 0x53, 0x74, 0x92, 0x3d, 0x94, 0x78, 0x90, 0xd0,
	0x7f, 0x90, 0x2c, 0x91, 0x42, 0x85, 0xd1, 0xa1, 0xa3, 0xba, 0x0b, 0x49, 0xd8, 0xc8, 0x68, 0x41,
	0xff, 0x3e, 0x30, 0x0b, 0xaf, 0x8f, 0xc7, 0x9b, 0xf9, 0x20, 0x7a, 0x27, 0xd3, 0x4d, 0x5d, 0x3e,
	0x33, 0xad, 0x84, 0x62, 0xb1, 0xfc, 0x35, 0x0e, 0x56, 0x5d, 0xc3, 0x69, 0x4d, 0x3d, 0x26, 0x10,
	0x1a, 0xbb, 0x0c, 0x3c, 0xce, 0xeb, 0x48, 0x1f, 0x17, 0x6e, 0xe2, 0xa6, 0xe7, 0xed, 0x11, 0x29,
	0x01, 0xbe, 0x9e, 0xe6, 0xf5, 0x5b, 0x95, 0xe0, 0x6b, 0x66, 0x62, 0xcc, 0x40, 0x58, 0xe6, 0x8a,
	0x8c, 0xdd, 0xfc, 0xb8, 0x90, 0xf9, 0x5e, 0xcd, 0xf5, 0x2f, 0x6f, 0xff, 0x84, 0x2c, 0x05, 0xb1,
	0x33, 0x0c, 0xe0, 0xe4, 0xb1, 0x91, 0x0e, 0x9e, 0x81, 0x77, 0xfb, 0xf2, 0xfc, 0x2a, 0x5d, 0x0c,
	0x41, 0xdc, 0xe9, 0x07, 0xdd, 0xde, 0x57, 0xd2, 0x14, 0x37, 0x10, 0x34, 0xdb, 0xa7, 0x78, 0x05,
	0xde, 0xd3, 0xe7, 0xf2, 0x86, 0xd1, 0x7f, 0xb6, 0xa6, 0xfe, 0x32, 0x3e, 0x1e, 0x21, 0x56, 0x4e,
	0x1f, 0x6c, 0x93, 0xca, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0xaa, 0xc4, 0xf4, 0xe2, 0x00,
	0x00, 0x00,
}
